version: '3.7'

services:
  mysql:
    image: percona:8.0
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: larabank
      MYSQL_USER: root

  app:
    build:
      context: .
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:1.17.9-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
